# Generated by Django 5.2 on 2025-04-12 09:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('half_life', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('delivered_activity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.TimeField(default=datetime.datetime.now)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiopharma.compound')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiopharma.compound')),
            ],
        ),
        migrations.CreateModel(
            name='UsedDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_activity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('use_time', models.TimeField(default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiopharma.batch')),
            ],
        ),
    ]
