# Generated by Django 5.2 on 2025-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiopharma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
    ]
