# Generated by Django 5.2 on 2025-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiopharma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikingTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='milkable',
            field=models.BooleanField(default=False),
        ),
    ]
