# Generated by Django 5.2 on 2025-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiopharma', '0002_batch_discarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='delivery_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='useddose',
            name='use_time',
            field=models.TimeField(),
        ),
    ]
