# Generated by Django 5.2 on 2025-04-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiopharma', '0002_mikingtimes_compound_milkable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MikingTimes',
        ),
    ]
