# Generated by Django 5.2 on 2025-04-12 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radiopharma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required_specific_dose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('required_fixed_dose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accumulation_time', models.IntegerField()),
                ('measuring_time', models.IntegerField()),
                ('accumulation_time2', models.IntegerField(blank=True, null=True)),
                ('measuring_time2', models.IntegerField(blank=True, null=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiopharma.compound')),
            ],
        ),
    ]
