# Generated by Django 5.2 on 2025-04-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('procedures', '0001_initial'),
        ('radiopharma', '0003_alter_batch_delivery_time_alter_useddose_use_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qa_activity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiopharma.compound')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiopharma.deliverytimes')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('calculated', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.procedure')),
            ],
        ),
    ]
